<?php
return array(
	//************* Shortcode << ****************
	'blog-column'=>array(
		esc_html__('One', 'slzexploore-core')   => '1',
		esc_html__('Two', 'slzexploore-core')   => '2',
		esc_html__('Three', 'slzexploore-core') => '3',
	),
	'h-tag'=>array(
		'H1'=>'h1',
		'H2'=>'h2',
		'H3'=>'h3',
		'H4'=>'h4',
		'H5'=>'h5',
		'H6'=>'h6',
	),
	'text-transform' => array(
		esc_html__('None', 'slzexploore-core')       => 'none',
		esc_html__('Capitalize', 'slzexploore-core') => 'capitalize',
		esc_html__('Uppercase', 'slzexploore-core')  => 'uppercase',
		esc_html__('Lowercase', 'slzexploore-core')  => 'lowercase',
		esc_html__('Initial', 'slzexploore-core')    => 'initial',
		esc_html__('Inherit', 'slzexploore-core')    => 'inherit',
	),
	'sort-blog' => array(
		esc_html__( '- Latest -', 'slzexploore-core' )               => '',
		esc_html__( 'A to Z', 'slzexploore-core' )                   => 'az_order',
		esc_html__( 'Z to A', 'slzexploore-core' )                   => 'za_order',
		esc_html__( 'Random posts today', 'slzexploore-core' )       => 'random_today',
		esc_html__( 'Random posts a week ago', 'slzexploore-core' )  => 'random_7_day',
		esc_html__( 'Random posts a month ago', 'slzexploore-core' ) => 'random_month',
		esc_html__( 'Random Posts', 'slzexploore-core' )             => 'random_posts',
		esc_html__( 'Most Commented', 'slzexploore-core' )           => 'comment_count',
	),
	'icon_type' => array(
		esc_html__( 'Exploore Icons', 'slzexploore-core' )          => '',
		esc_html__( 'Visual Composer Icons', 'slzexploore-core' )   => '02',
	),
	'align'=>array(
		esc_html__( 'Left', 'slzexploore-core' )   => 'left',
		esc_html__( 'Right', 'slzexploore-core' )  => 'right',
		esc_html__( 'Center', 'slzexploore-core' ) => 'center',
	),
	'sort-accomodation' => array(
		esc_html__( '- Latest -', 'slzexploore-core' )               => '',
		esc_html__( 'A to Z', 'slzexploore-core' )                   => 'az_order',
		esc_html__( 'Z to A', 'slzexploore-core' )                   => 'za_order',
		esc_html__( 'Price Ascending', 'slzexploore-core' )          => 'az_price',
		esc_html__( 'Price Descending', 'slzexploore-core' )         => 'za_price',
		esc_html__( 'Discount Ascending', 'slzexploore-core' )       => 'az_discount',
		esc_html__( 'Discount Descending', 'slzexploore-core' )      => 'za_discount',
		esc_html__( 'Star Rating Ascending', 'slzexploore-core' )    => 'az_star_rating',
		esc_html__( 'Star Rating Descending', 'slzexploore-core' )   => 'za_star_rating',
		esc_html__( 'Random', 'slzexploore-core' )                   => 'random_posts',
	),
	'sort-tour' => array(
		esc_html__( '- Latest -', 'slzexploore-core' )               => '',
		esc_html__( 'A to Z', 'slzexploore-core' )                   => 'az_order',
		esc_html__( 'Z to A', 'slzexploore-core' )                   => 'za_order',
		esc_html__( 'Tour Date Ascending', 'slzexploore-core' )      => 'az_start_date',
		esc_html__( 'Tour Date Descending', 'slzexploore-core' )     => 'za_start_date',
		esc_html__( 'Price Ascending', 'slzexploore-core' )          => 'az_price',
		esc_html__( 'Price Descending', 'slzexploore-core' )         => 'za_price',
		esc_html__( 'Discount Ascending', 'slzexploore-core' )       => 'az_discount',
		esc_html__( 'Discount Descending', 'slzexploore-core' )      => 'za_discount',
		esc_html__( 'Review Rating Ascending', 'slzexploore-core' )  => 'az_review_rating',
		esc_html__( 'Review Rating Descending', 'slzexploore-core' ) => 'za_review_rating',
		esc_html__( 'Random', 'slzexploore-core' )                   => 'random_posts',
	),
	'sort-cruise' => array(
		esc_html__( '- Latest -', 'slzexploore-core' )               => '',
		esc_html__( 'A to Z', 'slzexploore-core' )                   => 'az_order',
		esc_html__( 'Z to A', 'slzexploore-core' )                   => 'za_order',
		esc_html__( 'Departure Date Ascending', 'slzexploore-core' ) => 'az_start_date',
		esc_html__( 'Departure Date Descending', 'slzexploore-core' )=> 'za_start_date',
		esc_html__( 'Price Ascending', 'slzexploore-core' )          => 'az_price',
		esc_html__( 'Price Descending', 'slzexploore-core' )         => 'za_price',
		esc_html__( 'Discount Ascending', 'slzexploore-core' )       => 'az_discount',
		esc_html__( 'Discount Descending', 'slzexploore-core' )      => 'za_discount',
		esc_html__( 'Review Rating Ascending', 'slzexploore-core' )  => 'az_review_rating',
		esc_html__( 'Review Rating Descending', 'slzexploore-core' ) => 'za_review_rating',
		esc_html__( 'Random', 'slzexploore-core' )                   => 'random_posts',
	),
	'sort-car' => array(
		esc_html__( '- Latest -', 'slzexploore-core' )               => '',
		esc_html__( 'A to Z', 'slzexploore-core' )                   => 'az_order',
		esc_html__( 'Z to A', 'slzexploore-core' )                   => 'za_order',
		esc_html__( 'Price Ascending', 'slzexploore-core' )          => 'az_price',
		esc_html__( 'Price Descending', 'slzexploore-core' )         => 'za_price',
		esc_html__( 'Discount Ascending', 'slzexploore-core' )       => 'az_discount',
		esc_html__( 'Discount Descending', 'slzexploore-core' )      => 'za_discount',
		esc_html__( 'Review Rating Ascending', 'slzexploore-core' )  => 'az_review_rating',
		esc_html__( 'Review Rating Descending', 'slzexploore-core' ) => 'za_review_rating',
		esc_html__( 'Random', 'slzexploore-core' )                   => 'random_posts',
	),
	'sort-other' => array(
		esc_html__( '- Latest -', 'slzexploore-core' )     => '',
		esc_html__('A to Z', 'slzexploore-core')           => 'az_order',
		esc_html__('Z to A', 'slzexploore-core')           => 'za_order',
		esc_html__('Post is selected', 'slzexploore-core') => 'post__in',
		esc_html__('Random', 'slzexploore-core')           => 'random_posts',
	),
	'filter-hotel' => array(
		''                  => esc_html__( '- Latest -', 'slzexploore-core' ),
		'az_order'          => esc_html__('Name - Ascending', 'slzexploore-core'),
		'za_order'          => esc_html__('Name - Descending', 'slzexploore-core'),
		'az_star_rating'    => esc_html__('Star Rating - Ascending', 'slzexploore-core'),
		'za_star_rating'    => esc_html__('Star Rating - Descending', 'slzexploore-core'),
		'az_review_rating'  => esc_html__('Review Rating - Ascending', 'slzexploore-core'),
		'za_review_rating'  => esc_html__('Review Rating - Descending', 'slzexploore-core'),
		'az_discount'       => esc_html__('Discount - Low to High', 'slzexploore-core'),
		'za_discount'       => esc_html__('Discount - High to Low', 'slzexploore-core'),
		'az_price'          => esc_html__('Price - Low to High', 'slzexploore-core'),
		'za_price'          => esc_html__('Price - High to Low', 'slzexploore-core')
	),
	'filter-tour' => array(
		''                  => esc_html__( '- Latest -', 'slzexploore-core' ),
		'az_order'          => esc_html__('Name - Ascending', 'slzexploore-core'),
		'za_order'          => esc_html__('Name - Descending', 'slzexploore-core'),
		'az_start_date'     => esc_html__('Tour Date - Ascending', 'slzexploore-core'),
		'za_start_date'     => esc_html__('Tour Date - Descending', 'slzexploore-core'),
		'az_review_rating'  => esc_html__('Review Rating - Ascending', 'slzexploore-core'),
		'za_review_rating'  => esc_html__('Review Rating - Descending', 'slzexploore-core'),
		'az_discount'       => esc_html__('Discount - Low to High', 'slzexploore-core'),
		'za_discount'       => esc_html__('Discount - High to Low', 'slzexploore-core'),
		'az_price'          => esc_html__('Price - Low to High', 'slzexploore-core'),
		'za_price'          => esc_html__('Price - High to Low', 'slzexploore-core')
	),
	'filter-car' => array(
		''                  => esc_html__( '- Latest -', 'slzexploore-core' ),
		'az_order'          => esc_html__('Name - Ascending', 'slzexploore-core'),
		'za_order'          => esc_html__('Name - Descending', 'slzexploore-core'),
		'az_review_rating'  => esc_html__('Review Rating - Ascending', 'slzexploore-core'),
		'za_review_rating'  => esc_html__('Review Rating - Descending', 'slzexploore-core'),
		'az_discount'       => esc_html__('Discount - Low to High', 'slzexploore-core'),
		'za_discount'       => esc_html__('Discount - High to Low', 'slzexploore-core'),
		'az_price'          => esc_html__('Price - Low to High', 'slzexploore-core'),
		'za_price'          => esc_html__('Price - High to Low', 'slzexploore-core')
	),
	'filter-cruise' => array(
		''                  => esc_html__( '- Latest -', 'slzexploore-core' ),
		'az_order'          => esc_html__('Name - Ascending', 'slzexploore-core'),
		'za_order'          => esc_html__('Name - Descending', 'slzexploore-core'),
		'az_start_date'     => esc_html__('Departure Date - Ascending', 'slzexploore-core'),
		'za_start_date'     => esc_html__('Departure Date - Descending', 'slzexploore-core'),
		'az_star_rating'    => esc_html__('Star Rating - Ascending', 'slzexploore-core'),
		'za_star_rating'    => esc_html__('Star Rating - Descending', 'slzexploore-core'),
		'az_review_rating'  => esc_html__('Review Rating - Ascending', 'slzexploore-core'),
		'za_review_rating'  => esc_html__('Review Rating - Descending', 'slzexploore-core'),
		'az_discount'       => esc_html__('Discount - Low to High', 'slzexploore-core'),
		'za_discount'       => esc_html__('Discount - High to Low', 'slzexploore-core'),
		'az_price'          => esc_html__('Price - Low to High', 'slzexploore-core'),
		'za_price'          => esc_html__('Price - High to Low', 'slzexploore-core')
	),
	'featured-filter' => array(
		esc_html__( 'None', 'slzexploore-core' )     => '',
		esc_html__('Featured', 'slzexploore-core')   => '1'
	),
	//************* Shortcode >> ****************
	//************* Metabox << ****************
	'video-type' => array(
		''              => '',
		'vimeo'         => esc_html__( 'Vimeo','slzexploore-core' ),
		'youtube'       => esc_html__( 'Youtube','slzexploore-core' ),
	),
	'teammbox-social' => array(
		'facebook'      => esc_html__( 'Facebook', 'slzexploore-core' ),
		'twitter'       => esc_html__( 'Twitter', 'slzexploore-core' ),
		'google-plus'   => esc_html__( 'Google+', 'slzexploore-core' ),
		'youtube'       => esc_html__( 'YouTube', 'slzexploore-core' ),
		'rss'           => esc_html__( 'RSS', 'slzexploore-core' ),
		'delicious'     => esc_html__( 'Delicious', 'slzexploore-core' ),
		'flickr'        => esc_html__( 'Flickr', 'slzexploore-core' ),
		'lastfm'        => esc_html__( 'Lastfm', 'slzexploore-core' ),
		'linkedin'      => esc_html__( 'Linkedin', 'slzexploore-core' ),
		'vimeo'         => esc_html__( 'Vimeo', 'slzexploore-core' ),
		'tumblr'        => esc_html__( 'Tumblr', 'slzexploore-core' ),
		'pinterest'     => esc_html__( 'Pinterest', 'slzexploore-core' ),
		'deviantart'    => esc_html__( 'Deviantart', 'slzexploore-core' ),
		'git'           => esc_html__( 'Github', 'slzexploore-core' ),
		'instagram'     => esc_html__( 'Instagram', 'slzexploore-core' ),
		'stumbleupon'   => esc_html__( 'Stumbleupon', 'slzexploore-core' ),
		'behance'       => esc_html__( 'Behance', 'slzexploore-core' ),
		'tripadvisor'   => esc_html__( 'TripAdvisor', 'slzexploore-core' ),
		'vk'            => esc_html__( 'VK', 'slzexploore-core' ),
		'foursquare'    => esc_html__( 'Foursquare', 'slzexploore-core' ),
		'xing'          => esc_html__( 'XING', 'slzexploore-core' ),
		'weibo'         => esc_html__( 'Weibo', 'slzexploore-core' ),
		'odnoklassniki' => esc_html__( 'Odnoklassniki', 'slzexploore-core' ),
	),

	//************* Tour date type >> ****************
	'date_type' => array(
		'0' => esc_html__('None', 'slzexploore-core'),
		'1' => esc_html__('Fixed', 'slzexploore-core'),
		'2' => esc_html__('Duration', 'slzexploore-core'),
	),

	//************* Metabox >> ****************
	//************* Image Size ****************
	'block-image-size' => array(
		'tour_carousel'         => array( 'large' => '400x270' ),
		'tour'                  => array( 'large' => '400x270' ),
		'accommodation'         => array( 'large' => '800x540' ),
		'team_carousel'         => array( 'large' => '260x365' ),
		'team_single'           => array( 'large' => '200x200' ),
		'recent_news'           => array( 'large' => '670x440' ),
		'gallery_masonry_grid'  => array( 'large' => '670x440' ),
		'gallery_medium_image_slider'   => array( 'large' => '750x350' ),
		'gallery_large_image_slider'    => array( 'large' => '1140x515' ),
		'gallery_medium_image_slider_2' => array( 'large' => '900x500' ),
		'gallery_image_grid'    => array( 'large' => '100x100' ),
		'carousel'              => array( 'large' => '342x257' ),
		'room'                  => array( 'large' => '600x270', 'small' => '116x63' ),
		'testimonial'       	=> array( 'large' => '', 'small' => '200x200', 'no-image-small' => '200x200' ),
		'column-3'				=> array( 'large' => '100x100' ),
		'cruise'                => array( 'large' => '560x420' ),
		'car'                   => array( 'large' => '800x540' ),
		'wg_tour'               => array( 'large' => '100x80' ),
		'wg_hotel'              => array( 'large' => '100x80' ),
		'wg_cruise'             => array( 'large' => '100x80' ),
		'wg_car'                => array( 'large' => '100x80' ),
		'wg_gallery'            => array( 'large' => '560x420', 'small' => '100x100', 'no-image-small' => '100x100' ),

	),
);