<?php
return array(
	'author-social-links' =>array(
		'behance'       => esc_html__( 'Behance', 'exploore' ),
		'delicious'     => esc_html__( 'Delicious', 'exploore' ),
		'deviantart'    => esc_html__( 'Deviantart', 'exploore' ),
		'facebook'      => esc_html__( 'Facebook', 'exploore' ),
		'flickr'        => esc_html__( 'Flickr', 'exploore' ),
		'foursquare'    => esc_html__( 'Foursquare', 'exploore' ),
		'lastfm'        => esc_html__( 'Lastfm', 'exploore' ),
		'linkedin'      => esc_html__( 'Linkedin', 'exploore' ),
		'git'           => esc_html__( 'Github', 'exploore' ),
		'google-plus'   => esc_html__( 'Google+', 'exploore' ),
		'instagram'     => esc_html__( 'Instagram', 'exploore' ),
		'odnoklassniki' => esc_html__( 'Odnoklassniki', 'exploore' ),
		'pinterest'     => esc_html__( 'Pinterest', 'exploore' ),
		'rss'           => esc_html__( 'RSS', 'exploore' ),
		'skype'         => esc_html__( 'Skype', 'exploore' ),
		'soundcloud'    => esc_html__( 'Soundcloud', 'exploore' ),
		'stumbleupon'   => esc_html__( 'Stumbleupon', 'exploore' ),
		'tripAdvisor'   => esc_html__( 'TripAdvisor', 'exploore' ),
		'tumblr'        => esc_html__( 'Tumblr', 'exploore' ),
		'twitter'       => esc_html__( 'Twitter', 'exploore' ),
		'vimeo'         => esc_html__( 'Vimeo', 'exploore' ),
		'vk'            => esc_html__( 'VK', 'exploore' ),
		'weibo'         => esc_html__( 'Weibo', 'exploore' ),
		'xing'          => esc_html__( 'XING', 'exploore' ),
		'youtube'       => esc_html__( 'YouTube', 'exploore' ),
	),
	'header-social' => array(
		'facebook'   => 'fa-facebook',
		'twitter'    => 'fa-twitter',
		'google-plus'=> 'fa-google-plus',
		'pinterest'  => 'fa-pinterest',
		'instagram'  => 'fa-instagram',
		'dribbble'   => 'fa-dribbble',
	),
	'footer-social' => array(
		'facebook'   => 'fa-facebook',
		'twitter'    => 'fa-twitter',
		'google-plus'=> 'fa-google-plus',
		'pinterest'  => 'fa-pinterest',
		'instagram'  => 'fa-instagram',
		'dribbble'   => 'fa-dribbble',
		'facebook'   => 'fa-facebook',
	),
	'social-icons' =>array(
		'facebook'      => 'fa-facebook',
		'twitter'       => 'fa-twitter',
		'google-plus'   => 'fa-google-plus',
		'skype'         => 'fa-skype',
		'youtube'       => 'fa-youtube',
		'rss'           => 'fa-rss',
		'delicious'     => 'fa-delicious',
		'flickr'        => 'fa-flickr',
		'lastfm'        => 'fa-lastfm',
		'linkedin'      => 'fa-linkedin',
		'vimeo'         => 'fa-vimeo',
		'tumblr'        => 'fa-tumblr',
		'pinterest'     => 'fa-pinterest',
		'deviantart'    => 'fa-deviantart',
		'git'           => 'fa-git',
		'instagram'     => 'fa-instagram',
		'soundcloud'    => 'fa-soundcloud',
		'stumbleupon'   => 'fa-stumbleupon',
		'behance'       => 'fa-behance',
		'tripAdvisor'   => 'fa-tripadvisor',
		'vk'            => 'fa-vk',
		'foursquare'    => 'fa-foursquare',
		'xing'          => 'fa-xing',
		'weibo'         => 'fa-weibo',
		'odnoklassniki' => 'fa-odnoklassniki',
	),
	'sort_blog' => array(
		''              => esc_html__( '- Latest -', 'exploore' ),
		'az_order'      => esc_html__( 'A to Z', 'exploore' ),
		'za_order'      => esc_html__( 'Z to A', 'exploore' ),
		'random_today'  => esc_html__( 'Random posts today', 'exploore' ),
		'random_7_day'  => esc_html__( 'Random posts a week ago', 'exploore' ),
		'random_month'  => esc_html__( 'Random posts a month ago', 'exploore' ),
		'random_posts'  => esc_html__( 'Random Posts', 'exploore' ),
		'comment_count' => esc_html__( 'Most Commented', 'exploore' ),
		'popular'       => esc_html__( 'Popular', 'exploore' ),
	),
	// ---------- Editor Formats -----------------
	'style_formats' => array(
		'slzexploore_dropcap' => array(
			'title' => esc_html__( 'Dropcaps', 'exploore' ),
			'items' => array(
				array(
					'parent_id' => 'slzexploore_dropcap',
					'title'     => esc_html__( 'Box', 'exploore' ),
					'classes'   => 'dropcap',
					'inline'    => 'span',
				),
				array(
					'parent_id' => 'slzexploore_dropcap',
					'title'     => esc_html__( 'Circle', 'exploore' ),
					'classes'   => 'dropcap1',
					'inline'    => 'span',
				),
				array(
					'parent_id' => 'slzexploore_dropcap',
					'title'     => esc_html__( 'Regular', 'exploore' ),
					'classes'   => 'dropcap2',
					'inline'    => 'span',
				),
				array(
					'parent_id' => 'slzexploore_dropcap',
					'title'     => esc_html__( 'Bold', 'exploore' ),
					'classes'   => 'dropcap3',
					'inline'    => 'span',
				),
			)
		),
		'slzexploore_text_highlight' => array(
			'title' => esc_html__( 'Text highlighting', 'exploore' ),
			'items' => array(
				array(
					'parent_id' => 'slzexploore_text_highlight',
					'title'     => esc_html__( 'Black censured', 'exploore' ),
					'classes'   => 'highlight',
					'inline'    => 'span',
				),
				array(
					'parent_id' => 'slzexploore_text_highlight',
					'title'     => esc_html__( 'Red marker', 'exploore' ),
					'classes'   => 'highlight_maker red',
					'inline'    => 'span',
				),
				array(
					'parent_id' => 'slzexploore_text_highlight',
					'title'     => esc_html__('Blue marker', 'exploore' ),
					'classes'   => 'highlight_maker blue',
					'inline'    => 'span',
				),
				array(
					'parent_id' => 'slzexploore_text_highlight',
					'title'     => esc_html__( 'Green marker', 'exploore' ),
					'classes'   => 'highlight_maker green',
					'inline'    => 'span',
				),
				array(
					'parent_id' => 'slzexploore_text_highlight',
					'title'     => esc_html__( 'Yellow  marker', 'exploore' ),
					'classes'   => 'highlight_maker yellow ',
					'inline'    => 'span',
				),
				array(
					'parent_id' => 'slzexploore_text_highlight',
					'title'     => esc_html__( 'Pink  marker', 'exploore' ),
					'classes'   => 'highlight_maker pink ',
					'inline'    => 'span',
				),
			)
		),
		'slzexploore_blockquote' => array(
			'title' => esc_html__( 'Text Blockquote', 'exploore' ),
			'items' => array(
				array(
					'parent_id' => 'slzexploore_blockquote',
					'title'		=> esc_html__( 'Style 01', 'exploore' ),
					'block'		=> 'blockquote',
					'classes'	=> 'blockquote-01 blockquote',
					'wrapper'	=> true,
				),
				array(
					'parent_id' => 'slzexploore_blockquote',
					'title'     => esc_html__( 'Style 02', 'exploore' ),
					'block'		=> 'blockquote',
					'classes'	=> 'blockquote-02 blockquote',
					'wrapper'	=> true,
				),
				array(
					'parent_id' => 'slzexploore_blockquote',
					'title'     => esc_html__( 'Style 03', 'exploore' ),
					'block'		=> 'blockquote',
					'classes'	=> 'blockquote-03 blockquote',
					'wrapper'	=> true,
				),
				array(
					'parent_id' => 'slzexploore_blockquote',
					'title'     => esc_html__( 'Style 04', 'exploore' ),
					'block'     => 'blockquote',
					'classes'   => 'blockquote-04 blockquote',
					'wrapper'   => true,
				),
			)
		)
	),
	// image size
	'default-image-size' => array(
		'wg_recent_post'      => array( 'large' => '100x80' ),
		'blog'                => array( 'large' => '100x100' ),
		'author'              => array( 'large' => '600x270' ),
	),
	//************* CustomPost/ Page Setting << ****************
	'video-type' => array(
		'video-upload'  => esc_html__( 'Self-Hosted Video', 'exploore' ),
		'vimeo'         => esc_html__( 'Vimeo', 'exploore' ),
		'youtube'       => esc_html__( 'Youtube', 'exploore' ),
	),
	'background-repeat' => array(
		''          => esc_html__( '-Background Repeat-', 'exploore' ),
		'no-repeat' => esc_html__( 'No Repeat', 'exploore' ),
		'repeat'    => esc_html__( 'Repeat All', 'exploore' ),
		'repeat-x'  => esc_html__( 'Repeat Horizontally', 'exploore' ),
		'repeat-y'  => esc_html__( 'Repeat Vertically', 'exploore' ),
		'inherit'   => esc_html__( 'Inherit', 'exploore' ),
	),
	'background-size' => array(
		''        => esc_html__( '-Background Size-', 'exploore' ),
		'inherit' => esc_html__( 'Inherit', 'exploore' ),
		'cover'   => esc_html__( 'Cover', 'exploore' ),
		'contain' => esc_html__( 'Contain', 'exploore' ),
	),
	'background-position' => array(
		''              => esc_html__( '-Background Position-', 'exploore' ),
		'left top'      => esc_html__( 'Left Top', 'exploore' ),
		'left center'   => esc_html__( 'Left center', 'exploore' ),
		'left bottom'   => esc_html__( 'Left Bottom', 'exploore' ),
		'center top'    => esc_html__( 'Center Top', 'exploore' ),
		'center center' => esc_html__( 'Center Center', 'exploore' ),
		'center bottom' => esc_html__( 'Center Bottom', 'exploore' ),
		'right top'     => esc_html__( 'Right Top', 'exploore' ),
		'right center'  => esc_html__( 'Right center', 'exploore' ),
		'right bottom'  => esc_html__( 'Right Bottom', 'exploore' ),
	),
	'background-attachment' => array(
		''        => esc_html__( '-Background Attachment-', 'exploore' ),
		'fixed'   => esc_html__( 'Fixed', 'exploore' ),
		'scroll'  => esc_html__( 'Scroll', 'exploore' ),
		'inherit' => esc_html__( 'Inherit', 'exploore' ),
	),
	'sidebar-layout' => array(
		'none'  => esc_html__( 'None', 'exploore' ),
		'left'  => esc_html__( 'Left', 'exploore' ),
		'right' => esc_html__( 'Right', 'exploore' ),
	),
	'header_layout' => array(
		'one'   => 'style_1.png',
		'two'   => 'style_2.png',
		'three' => 'style_3.png',
		'four'  => 'style_4.png',
		'five'  => 'style_5.png',
	),
	//************* Page Setting >> ****************
);